version: '3.0'
services:
  hello_world_client :
      build:
        #specifiy the project build context
        context: .
        #specifiy the Dockerfile to use
        dockerfile: Dockerfile
      restart: always
      #bind host port 8989 to container port 8080
      ports:
         - 8989:80
